version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      all-updates:
        patterns:
          - "*" # Group all into one

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    groups:
      all-updates:
        patterns:
          - "*" # Group all into one
